### ISSUE TITLE
투명성을 위한 움직임 중 계약서를 투명하게 개방하자는 운동이 있어요 - Open Contracting

### ISSUE THREAD

**Issue by thechunsik** [codeforseoul/seoulproblems#12]
[Where Does My Money Go?] (http://wheredoesmymoneygo.kr)이 예산의 투명성을 위한 [Open Spending] (http://openspending.org/)의 일환이라면 계약서를 투명하게 공개하자는 [Open Contracting] (http://www.open-contracting.org/)이 있어요. 최근에 계약서 표준 양식도 1.0 버전으로 발표되었구요. 혹시 함께 스터디해보실 분 있나요? 가능하면 장기적으로는 우리나라 계약서 데이터도 이 표준엔 맞게 쉽게 국민들이 볼 수 있는 사이트를 만들어보고 싶어요.

**Comment by hoony-o-1** [comment]
moved to #14 for transparency
